config/routes.rb
Rails.application.routes.draw do
  resources :cities

  post 'cities/find_city_by_query' => 'cities#find_city_by_query', as: :find_city_query_api
  post 'cities/find_city_by_geolocation' => 'cities#find_city_by_geolocation', as: :find_city_geo_api
  post 'cities/find_city_by_zip_code' => 'cities#find_city_by_zip_code', as: :find_city_zip_api

  get 'home/update', to: 'home#update'
  get 'home/fetch_wind_conditions', to: 'home#fetch_wind_conditions'

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @forecast = nil
  end

  def set_params
    params.require(:city).permit(:city_id)
  end

  def update
    city = City.find(set_params[:city_id])
    previous_forecast = CityForecast.where(city: city.id).last
    if previous_forecast.nil? or previous_forecast.updated_at.to_date < Date.today()
      forecast_json = GetForecast.new().get_5_day_forecast(city.location_key)
      if forecast_json.is_a?(Hash) and forecast_json.key?("Message")
        flash[:danger] = 'Error de API: "' + forecast_json["Message"] + '"'
      else
        @forecast = CityForecastFactory.new().create_from_json(city, forecast_json["DailyForecasts"])
      end
    else
      @forecast = previous_forecast
    end
    @wind_direction = @forecast.forecasts[0].wind_direction
    @wind_speed = @forecast.forecasts[0].wind_speed
    @city_id = city.id
    respond_to do |format|
      format.js { render 'home/update_city.js.erb', locals: {forecast: @forecast, wind_direction: @wind_direction, wind_speed: @wind_speed, city_id: @city_id} }
    end
  end

  def fetch_wind_conditions
    city = City.find(set_params[:city_id])
    forecast_json = GetCurrentConditions.new().get_current_conditions(city.location_key)
    if forecast_json.is_a?(Hash) and forecast_json.key?("Message")
      flash[:danger] = 'Error de API: "' + forecast_json["Message"] + '"'
    else
      @wind_direction = forecast_json[0]["Wind"]["Direction"]["Localized"]
      @wind_speed = forecast_json[0]["Wind"]["Speed"]["Metric"]["Value"]
      @city_id = city.id
    end
    respond_to do |format|
      format.js { render 'home/update_wind.js.erb', locals: {wind_direction: @wind_direction, wind_speed: @wind_speed, city_id: @city_id } }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def get_wind_direction_image_path(wind_direction)
    path = ""
    case wind_direction
      when "N"
        path = "wind-n.png"
      when "NNE"
        path = "wind-nne.png"
      when "NE"
        path = "wind-ne.png"
      when "ENE"
        path = "wind-ene.png"
      when "E"
        path = "wind-e.png"
      when "ESE"
        path = "wind-ese.png"
      when "SE"
        path = "wind-se.png"
      when "SSE"
        path = "wind-sse.png"
      when "S"
        path = "wind-s.png"
      when "SSW"
        path = "wind-sso.png"
      when "SW"
        path = "wind-so.png"
      when "WSW"
        path = "wind-oso.png"
      when "W"
        path = "wind-o.png"
      when "WNW"
        path = "wind-ono.png"
      when "NW"
        path = "wind-no.png"
      when "NNW"
        path = "wind-nno.png"
    end
    path
  end
end

app/views/home/_chart.html.erb
<% if @forecast %>
  <% @forecasts = @forecast.forecasts %>
  <div class="row" style="margin-top: 30px">
    <div class="col-md-12">
      <div align="center">
        <% @highcharts_data = @forecasts.map {|day| [day.date.to_date(), day.max_temperature]} %>
        <% @highcharts_colors = @forecasts.map {|day| day.get_cloud_cover_color } %>
        <div align="center">
          <h3 style="font-weight: bold">Gráfico de Temperatura Máxima</h3>
        </div>
        <div class="row row-centered" style="margin-top: 20px;">
          <div class="col-md-9">
            <%= column_chart @highcharts_data, suffix:" °C", colors: @highcharts_colors.pluck(:color),
                             adapter: "highcharts", library: {"plotOptions": {"series": {"colorByPoint": true }}} %>
          </div>
          <div class="col-md-3">
            <div class="panel panel-default">
              <div class="panel-heading">
                <div align="center">
                  <h4 style="font-weight: bold">Leyenda</h4>
                </div>
                <% max_temperature_map = @forecasts.map{|day| day.max_temperature.to_d} %>
                <% min_temperature_map = @forecasts.map{|day| day.min_temperature.to_d} %>
                <table class="table" style="margin-top: 20px; table-layout: fixed; border-collapse:separate; border-spacing:5px;">
                  <tbody>
                  <% for color in @highcharts_colors.uniq.sort_by {|col| col[:legend]} %>
                      <tr>
                        <td style="border-top: none; background-color: <%= color[:color] %>"></td>
                        <td style="border-top: none;"><%= color[:legend] %> Nubosidad</td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_city_selection_form.html.erb
<div style="margin-top: 20px">
  <%= form_for :city, url: home_update_path, remote: true, method: :get do |f| %>
      <div class="row row-centered">
        <div class="col-md-12 col-centered">
          <div class="">
            <%= f.select :city_id, City.all.map{|city| [city.to_s, city.id]}, class: 'js-searchable' %>
          </div>
        </div>
      </div>
      <div class="center" style="margin-top: 20px">
        <%= f.submit 'Aplicar', class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/home/_detail.html.erb
<% if @forecast %>
  <% @forecasts = @forecast.forecasts %>
  <div class="row" style="margin-top: 30px">
    <div class="col-md-12">
      <div style="margin-top: 50px">
        <div align="center">
          <h3 style="font-weight: bold">Detalle Pronóstico</h3>
        </div>
        <table id="forecast-table" class="table table-striped table-bordered table-condensed display responsive no-wrap">
          <thead>
          <tr>
            <th>Día</th>
            <th>T° Mínima</th>
            <th>T° Máxima</th>
            <th>Viento</th>
            <th>Nubosidad</th>
          </tr>
          </thead>
          <tbody>
          <% @forecasts.each do |day| %>
              <tr>
                <td><%= day.date.to_date %></td>
                <td><%= day.min_temperature %> °C</td>
                <td><%= day.max_temperature %> °C</td>
                <td><%= day.wind_speed %> km/h (dir: <%= day.wind_direction %>)</td>
                <td><%= day.cloud_cover %>%</td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_summary.html.erb
<% if @forecast %>
  <div align="center">
    <h1>PRONÓSTICO A 5 DÍAS PARA <b><%= @forecast.city.to_s.upcase %></b></h1>
  </div>
  <% @forecasts = @forecast.forecasts %>
  <div class="row" style="margin-top: 30px">
    <div class="col-md-12">
      <div align="center">
        <h3 style="font-weight: bold">Resumen Prónostico de Temperatura</h3>
      </div>
      <div class="row row-centered" style="margin-top: 20px;">
        <div class="col-md-6 col-centered">
          <div class="panel panel-default">
            <div class="panel-heading">
              <% max_temperature_map = @forecasts.map{|day| day.max_temperature.to_d} %>
              <% min_temperature_map = @forecasts.map{|day| day.min_temperature.to_d} %>
              <table class="table table-condensed table-bordered"  style="margin-top: 20px">
                <tbody>
                <tr>
                  <td><b>Promedio Máxima: </b></td>
                  <% max_avg = max_temperature_map.reduce(:+) / @forecasts.size %>
                  <td><%= max_avg.to_i %> °C</td>
                </tr>
                <tr>
                  <td><b>Promedio Mínima: </b></td>
                  <% min_avg = min_temperature_map.reduce(:+) / @forecasts.size %>
                  <td><%= min_avg.to_i %> °C</td>
                </tr>
                <tr>
                  <td><b>Promedio Del Periodo: </b></td>
                  <td><%= ((max_avg + min_avg) / 2).to_i %> °C</td>
                </tr>
                </tbody>
              </table>
              <table class="table table-condensed table-bordered"  style="margin-top: 20px">
                <tbody>
                <tr>
                  <td><b>Máxima Global: </b></td>
                  <td><%= max_temperature_map.max %> °C</td>
                </tr>
                <tr>
                  <td><b>Mínima Global: </b></td>
                  <td><%= min_temperature_map.min %> °C</td>
                </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_wind.html.erb
<% if @wind_direction and @wind_speed and @city_id %>
  <div class="row" style="margin-top: 30px">
    <div class="col-md-12">
      <div align="center">
        <h3 style="font-weight: bold">Dirección del Viento Actual</h3>
      </div>
      <div class="row row-centered" style="margin-top: 20px;">
        <div class="col-md-6 col-centered">
          <img style="display: inline-block" height="300px" src="<%= asset_path( get_wind_direction_image_path(@wind_direction) ) %>" />
          <div>
            <h3 style="display: inline-block; padding: 10px">Velocidad: <%= @wind_speed %> km/h</h3>
            <%= button_to "⟳", home_fetch_wind_conditions_path, form: {style: 'display:inline-block;'}, class:"btn btn-default", method: :get, remote: true, params: {:city =>{:city_id => @city_id}} %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<div class="row row-centered" style="margin-bottom: 20px; margin-top: 40px">
  <div class="col-md-6 col-centered">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 style="font-weight: bold">Pronóstico a 5 días</h4>
        <% if City.any? %>
          <%= render 'city_selection_form' %>
        <% else %>
            <p>
              Aún no se han registrado ciudades. Debes
              <%= link_to new_city_path do %>
                registrar una nueva ciudad
              <% end %>
               para consultar el pronóstico.
            </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid" style="margin-bottom: 150px">
  <div id="summary-partial">
    <%= render 'summary', locals: {forecast: @forecast} %>
  </div>
  <div id="chart-partial">
    <%= render 'chart', locals: {forecast: @forecast} %>
  </div>
  <div id="wind-partial">
    <%= render 'wind', locals: {wind_direction: @wind_direction, wind_speed: @wind_speed} %>
  </div>
  <div id="detail-partial">
    <%= render 'detail', locals: {forecast: @forecast} %>
  </div>
</div>

app/views/home/update_city.js.erb
$('#summary-partial').html("<%= escape_javascript(render partial: 'summary', :locals => { forecast: @forecast }) %>");
$('#chart-partial').html("<%= escape_javascript(render partial: 'chart', :locals => { forecast: @forecast }) %>");
$('#detail-partial').html("<%= escape_javascript(render partial: 'detail', :locals => { forecast: @forecast }) %>");
$('#wind-partial').html("<%= escape_javascript(render partial: 'wind', :locals => { wind_direction: @wind_direction, wind_speed: @wind_speed, city_id: @city_id }) %>");

app/views/home/update_wind.js.erb
$('#wind-partial').html("<%= escape_javascript(render partial: 'wind', :locals => { wind_direction: @wind_direction, wind_speed: @wind_speed, city_id: @city_id }) %>");