config/routes.rb
Rails.application.routes.draw do
  resources :cities

  post 'cities/find_city_by_query' => 'cities#find_city_by_query', as: :find_city_query_api
  post 'cities/find_city_by_geolocation' => 'cities#find_city_by_geolocation', as: :find_city_geo_api
  post 'cities/find_city_by_zip_code' => 'cities#find_city_by_zip_code', as: :find_city_zip_api

  get 'home/update', to: 'home#update'
  get 'home/fetch_wind_conditions', to: 'home#fetch_wind_conditions'

  root 'home#index'
end

app/models/city.rb
class City < ApplicationRecord
  validates :location_key, uniqueness: true
  has_many :city_forecasts, :dependent => :destroy

  def to_s
    name + ", " + country
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  def find_city_by_query
    cities = GetCities.new().get_cities_by_query(params[:city_query])
    if cities.is_a?(Hash) and cities.key?("Message")
      flash[:danger] = 'Error de API: "' + cities["Message"] + '"'
      redirect_to new_city_path
    else
      respond_to do |format|
        format.js { render :partial => 'cities/render_city_list_modal.js.erb', locals: {cities: cities.first(20)} }
      end
    end
  end

  def find_city_by_geolocation
    geolocation = params[:latitude] + "," + params[:longitude]
    cities = [GetCities.new().get_cities_by_geolocation(geolocation)]
    if cities.is_a?(Hash) and cities.key?("Message")
      flash[:danger] = 'Error de API: "' + cities["Message"] + '"'
      redirect_to new_city_path
    else
      respond_to do |format|
        format.js { render :partial => 'cities/render_city_list_modal.js.erb', locals: {cities: cities.first(20)} }
      end
    end
  end

  def find_city_by_zip_code
    cities = GetCities.new().get_cities_by_zip_code(params[:zip_code])
    if cities.is_a?(Hash) and cities.key?("Message")
      flash[:danger] = 'Error de API: "' + cities["Message"] + '"'
      redirect_to new_city_path
    else
      respond_to do |format|
        format.js { render :partial => 'cities/render_city_list_modal.js.erb', locals: {cities: cities.first(20)} }
      end
    end
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        flash[:success] = 'Ciudad Creada Exitosamente'
        format.html { redirect_to @city }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      flash[:success] = 'Ciudad Eliminada Exitosamente'
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.fetch(:city, {}).permit(:name, :country, :location_key)
    end
end

app/views/cities/_city_list_modal.html.erb
<div class="modal fade" id="cityModal" tabindex="-1" role="dialog" aria-labelledby="cityModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" >
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h1 class="modal-title" id="cityModalLabel">
          Guardar Nueva Ciudad
        </h1>
      </div>
      <div class="modal-body">
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Ciudad</th>
              <th>País</th>
              <th>Región</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% for city in cities %>
              <tr>
                <td><%= city["LocalizedName"] %></td>
                <td><%= city["Country"]["LocalizedName"] %></td>
                <td><%= city["AdministrativeArea"]["LocalizedName"] %></td>
                <td>
                  <% city_obj = {:city => {:name => city["LocalizedName"],
                                          :country => city["Country"]["LocalizedName"],
                                          :location_key => city["Key"]}}%>
                  <%= link_to "Guardar", cities_path(city_obj), :method => :post %>
                </td>
              </tr>
              <p></p>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/cities/_form_autocomplete.html.erb
<%= form_with(model: city, local: true) do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% cities = GetCities.new().get_cities("santiago")[:cities] %>
    <% if cities.key?("Message") %>
      <div id="error_explanation">
        <h2>No se pudo consultar la lista de ciudades</h2>

        <ul>
          <li>Accuweather error: <%= cities["Message"] %></li>
        </ul>
      </div>
    <% else %>
      <%= form.select "selector", options_for_select(cities.map{|a| a["LocalizedName"] + ', ' + a["Country"]["LocalizedName"]}) %>
        <%= form.submit %>
    <% end %>
    <div class="actions">
  </div>
<% end %>

app/views/cities/_form_city.html.erb
<%= form_tag(find_city_query_api_path, method: 'post', remote: true) do %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <label for="city_query">Ciudad</label>
    <%= text_field_tag :city_query %>

    <%= submit_tag("Buscar Ciudad", :style => "margin-left:10px;", class: "btn btn-success") %>
    <div class="actions">
  </div>
<% end %>

app/views/cities/_form_geo.html.erb
<%= form_tag(find_city_geo_api_path, method: 'post', remote: true) do %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <label for="latitude">Latitud</label>
    <%= text_field_tag :latitude %>
    <label for="longitude">Longitud</label>
    <%= text_field_tag :longitude %>

    <%= submit_tag("Buscar Ciudad", :style => "margin-left:10px;", class: "btn btn-success") %>
    <div class="actions">
  </div>
<% end %>

app/views/cities/_form_zip.html.erb
<%= form_tag(find_city_zip_api_path, method: 'post', remote: true) do %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <label for="zip_code">Código Postal</label>
    <%= text_field_tag :zip_code %>

    <%= submit_tag("Buscar Ciudad", :style => "margin-left:10px;", class: "btn btn-success") %>
    <div class="actions">
  </div>
<% end %>

app/views/cities/_render_city_list_modal.js.erb
$("#cityModalContent").html("<%= escape_javascript(render 'cities/city_list_modal', cities: cities) %>");
$("#cityModal").modal('show');

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<div class="row row-centered" style="margin-bottom: 20px; margin-top: 40px">
  <div class="col-md-6 col-centered">
      <h1>Ciudades</h1>
  </div>
</div>

<div class="row row-centered">
  <div class="col-md-10 col-centered">
    <div>
      <table id="city-table" class="table table-striped table-bordered table-condensed display responsive no-wrap">
        <thead>
        <tr>
          <th>Ciudad</th>
          <th>País</th>
          <th>Código</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @cities.each do |city| %>
            <tr>
              <td><%= city.name %></td>
              <td><%= city.country %></td>
              <td><%= city.location_key %></td>
              <td><%= link_to 'Ver', city %> | <%= link_to 'Eliminar', city, method: :delete, data: { confirm: 'Seguro que desea eliminar la ciudad?' } %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'Agregar Nueva Ciudad', new_city_path, class: "btn btn-success" %>
  </div>
</div>
<br>

app/views/cities/new.html.erb
<div id="cityModalContent">
</div>

<div class="row row-centered" style="margin-bottom: 20px; margin-top: 40px">
  <div class="col-md-6 col-centered">
    <h1>Agregar Nueva Ciudad</h1>
  </div>
</div>

<div class="row row-centered">
  <div class="col-md-10 col-centered">
    <div style="margin-bottom:30px">
      <p>Para agregar una nueva ciudad, seleccione un método de búsqueda y rellene los datos correpsondientes.</p>
      <div class="row row-centered" style="margin: 40px;">
          <%= select_tag "type_selector", options_for_select(["Nombre Ciudad", "Geolocalización", "Código Postal"]) %>
      </div>
      <div id='form_city'>
        <%= render 'form_city', city: @city %>
      </div>
      <div id='form_geo'>
        <%= render 'form_geo', city: @city %>
      </div>
      <div id='form_zip'>
        <%= render 'form_zip', city: @city %>
      </div>
    </div>
    <%= link_to 'Volver', cities_path, class: "btn btn-default" %>
  </div>
</div>
<br>

app/views/cities/show.html.erb
<h2></h2>



<div id="cityModalContent">
</div>

<div class="row row-centered" style="margin-bottom: 20px; margin-top: 40px">
  <div class="col-md-6 col-centered">
    <h1><b><%= @city.name %></b></h1>
    <h3><%= @city.country %></h3>

    <p style="margin-bottom: 30px">Código de locación: <%= @city.location_key %></p>

    <%= link_to 'Volver', cities_path, class: "btn btn-default" %>
  </div>
</div>